#!/usr/bin/env bash
#
# Description: makes logging easier in bash
# Dependencies: none
# Author: gawlk

# ---
# VARS
# ---

# Background
bblk="\e[40m"
bred="\e[41m"

# Foreground
fgry="\e[90m"
fred="\e[31m"
fgrn="\e[32m"
fblu="\e[34m"
fwht="\e[37m"

# ---
# LOCAL
# ---

print() {
    type="$1"
    title="$2"
    description="$3"
    fgrd="$4"
    bgrd="$5"
    echo -e "${fgry}[ ${bgrd}${fgrd}${type}${bblk} ${fgry}] ${fred}${title}${fgry}: ${fwht}${description}"
}

# ---
# GLOBAL
# ---

log.info() {
    [[ -z "$quiet" || "$quiet" == false ]] && print "  info " "$1" "$2" "$fblu"
}

log.debug() {
    [[ -n "$dev" && "$dev" == true ]] && print " debug " "$1" "$2" "$fgrn"
}

log.warning() {
    print "warning" "$1" "$2" "$fred"
}

log.error() {
    print " error " "$1" "$2" "$fwht" "$bred"
    exit 1
}

log.quit() {
    log.info "$1" "$2"
    exit 0
}

log.quiet() {
    quiet=true
}

log.loud() {
    quiet=false
}

log.dev() {
    dev=true
}

log.casual() {
    dev=false
}
